version: "3.9"  # optional since v1.27.0
services:
  # web:
  #   build: .
  #   ports:
  #     - "8000:5000"
  #   volumes:
  #     - .:/code
  #   links:
  #     - redis
  #     - logvolume01:/var/log
  redis:
    image: redislabs/redisearch:latest
    volumes:
      - ./data:/etc/redis/database
    ports:
      - 6379:6379
volumes:
  logvolume01: {}