name: Deploy to Signal

on:
  push:
    paths:
      - 'frontend/**'
      - '.github/workflows/*'
    branches:
      - "master"

jobs:
  zip-files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16.9.1'
          registry-url: 'https://registry.npmjs.org'
      - run: |
          cd frontend
          yarn
      - name: Build
        run: |
          cd frontend
          NODE_ENV=production
          yarn build
      - name: Edgeserver Upload
        uses: lvkdotsh/edgeserver-action@master
        with:
          app_id: "58153175907045376"
          server: https://api.edgeserver.io
          token: ${{ secrets.SIGNAL_TOKEN }}
          directory: frontend/dist/
          